### ISSUE TITLE
Html view not updating co-ops with no geolocation.

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/open-data#24]
Africa Confederation of Co-operative Savings & Credit Associations (ACCOSCA) appears as a co-op with an unresolvable geolocation and thus appears at the ICA headquarters, however it is missing from the html data here
https://data1.solidarityeconomy.coop/ICA/index.html

**Comment by dtmakm27** [comment]
@ColmMassey 

The data on the prod server does not have the most updated initiatives 
The dev.ica map is actually pointing towards https://dev.data.solidarityeconomy.coop/ICA/index.html

So there is not an issue here..

However, we need to untangle initiative urls in the dev and prod servers (which is already an issue), because it is causing some errors (i.e. if you search for Africa Confederation of Co-operative Savings and click on the initiative url it resolves to a 404 because it is attempting to find it on the production server)

This will get fixed when we detangle them or when I update production data.

Shall we close this?

**Comment by ColmMassey** [comment]
I'll de-assign and drop it off the project board, but I'll leave it open and linked to this 
https://github.com/SolidarityEconomyAssociation/open-data/issues/26
so it can act as a test for it.
